// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    acompanhamento: {
        name: "acompanhamento";
        parameters: Record<string, never>;
        result: Array<{
          /** Nome do vendedor responsável, via carteira vigente (silver.carteira -> silver.vendedores). */
          vendedor: string;
          /** @sqlType BIGINT */
          na_fila: number;
          /** @sqlType BIGINT */
          trabalhados: number;
          /** @sqlType BIGINT */
          vendeu: number;
          /** @sqlType BIGINT */
          vai_pensar: number;
          /** @sqlType BIGINT */
          sem_interesse: number;
          /** @sqlType BIGINT */
          nao_atendeu: number;
        }>;
      };
    fila: {
        name: "fila";
        parameters: {
          /** STRING - use sql.string() */
          vendedor: SQLStringMarker;
        };
        result: Array<{
          /** Nome do vendedor responsável, via carteira vigente (silver.carteira -> silver.vendedores). */
          vendedor: string;
          /** Posição do cliente na fila DAQUELE vendedor (1 = primeira ligação), não a posição global. */
          ordem: number;
          /** Identificador do cliente, mesmo cliente_id de gold.score_propensao e gold.dim_cliente. */
          cliente_id: string;
          /** Razão social do cliente, de gold.dim_cliente. */
          razao_social: string;
          /** Cidade do cliente, de gold.dim_cliente. */
          cidade: string;
          /** UF do cliente, de gold.dim_cliente. */
          uf: string;
          /** Probabilidade de compra na semana, de gold.score_propensao (0 a 1). Maior = mais prioritário. */
          score: number;
          /** Faixa do score em quartis: Fria, Morna, Quente, Muito quente (gold.score_propensao). */
          faixa: string;
          /** Ticket médio histórico do cliente, de gold.features_cliente. */
          ticket_medio: number;
          /** Frase em português explicando por que o cliente está na fila, com os números reais dele. Nunca nula — sempre tem um ELSE. */
          motivo: string;
          /** O que oferecer: o SKU mais comprado pelo cliente, na marca preferida dele, que ele não levou nos últimos 90 dias, com o saldo do snapshot mais recente de silver.estoque. */
          sugestao: string;
          /** Resultado da ligação: vendeu, vai_pensar, sem_interesse ou nao_atendeu. */
          retorno_status: string;
          /** Texto livre do vendedor sobre a ligação. */
          retorno_comentario: string;
        }>;
      };
    kpis_semana: {
        name: "kpis_semana";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType BIGINT */
          contatos: number;
          /** @sqlType BIGINT */
          vendedores: number;
          /** @sqlType DOUBLE */
          receita_esperada: number;
          /** @sqlType DATE */
          referencia: string;
          /** @sqlType BIGINT */
          acertos_top200: number;
          /** @sqlType DOUBLE */
          lift_top200: number;
          /** @sqlType DOUBLE */
          taxa_base: number;
          /** @sqlType BIGINT */
          versao: number;
          /** @sqlType BIGINT */
          ligacoes_registradas: number;
          /** @sqlType BIGINT */
          vendas: number;
        }>;
      };
    vendedores: {
        name: "vendedores";
        parameters: Record<string, never>;
        result: Array<{
          /** Nome do vendedor responsável, via carteira vigente (silver.carteira -> silver.vendedores). */
          vendedor: string;
          /** @sqlType BIGINT */
          contatos: number;
        }>;
      };
  }
}
